### ISSUE TITLE
xuefei-流式编程

### ISSUE THREAD

**Issue by haoyue1573** [briqt/xunfei-spark4j#10]
你好，我想问一下，这个流式编程的输出怎么配和前端展示出来呢

**Comment by briqt** [comment]
你可以通过继承SparkBaseListener，并重写其onMessage方法来处理流式编程的输出。在onMessage方法中，你可以获取到流式返回的当前文本。为了与前端展示配合，你可以使用WebSocket或者Server-Sent Events (SSE) 进行通信。当前端通过HTTP或WebSocket请求后端时，将WebSocket连接传递给自定义的SparkBaseListener，然后在onMessage方法中，通过WebSocket连接向前端发送数据。

**Comment by haoyue1573** [comment]
我主要是不知道用你这种api怎么和前端建立连接通道
单纯的使用spring-boot-websocket是直接使用几个注解就能进行监听了，你这种我是实在不会

**Comment by briqt** [comment]
1. 以SparkConsoleListener为例，将websocket的session作为成员变量
2. 发送请求时，将当前的session传到Listener中：sparkClient.chatStream(sparkRequest,new SparkConsoleListener(**session**));
3. 将消息从打印到控制台改为发送给客户端：system.out.println-->session.send
以上为伪代码

**Comment by haoyue1573** [comment]
博主，SparkBaseListener及其子类都没有有参构造，怎么传参?  还有一点就是基于websocket建立通信，也没说清啊，是否也需要  @OnMessage  @OnOpen  .. 这类注解  ，监听通道

**Comment by briqt** [comment]
这属于Java语言及Spring框架的技能了
