### ISSUE TITLE
同步调用，显示证书错误

### ISSUE THREAD

**Issue by lvxincao** [briqt/xunfei-spark4j#11]
avax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

下面是我的代码
![微信图片_20240418144823](https://github.com/briqt/xunfei-spark4j/assets/12597354/f4e4a11a-29c0-49dd-a51d-5e56f232f4ce)

**Comment by briqt** [comment]
我运行测试类一切正常，检查一下你的网络环境试试

**Comment by lvxincao** [comment]
单独运行测试类一切正常，加入tomcat做成web项目请求，就不行

**Comment by briqt** [comment]
开发测试和部署的网络环境都相同吗？如果网络环境相同，提供一下出错的环境的jre版本、tomcat版本，我试试能不能复现。

这个属于okhttp发送wss请求失败，也可以搜索相关解决方案。

**Comment by lvxincao** [comment]
tomcat8.5.13, jre 1.8.0_202

**Comment by lvxincao** [comment]
找到原因了。在虚拟机中设置了-Djsse.enableSNIExtension=false 我们设置了这么参数，导致请求讯飞这个接口就会报错
