### ISSUE TITLE
4.0用不了

### ISSUE THREAD

**Issue by saynotolose** [briqt/xunfei-spark4j#13]
是不是还没发布，我看maven仓库里修改时间还是1/31

**Comment by briqt** [comment]
先克隆到本地 mvn install 使用吧，我的 maven 仓库秘钥有些问题，在解决

**Comment by Scorn6** [comment]
还没好吗，哥

**Comment by TFboy1** [comment]
我也是4.0用不了，maven仓库好像还没更新

**Comment by Scorn6** [comment]
本人解决方法就是把代码clone下来然后往项目里面加

**Comment by TFboy1** [comment]
> 本人解决方法就是把代码clone下来然后往项目里面加

我知道这个方法很好，但是我这个是用来搞个比赛的，直接加进去的话，太臃肿不太好提交

**Comment by briqt** [comment]
我给忘记了...
现在发包，中央仓库可能会有一两天的延迟。

**Comment by briqt** [comment]
@TFboy1 @Scorn6 @saynotolose 
已经推送到 01.oss.sonatype.org 仓库。

https://s01.oss.sonatype.org/#nexus-search;quick~briqt

**Comment by TFboy1** [comment]
java.lang.NoSuchFieldError: Class io.github.briqt.spark4j.constant.SparkApiVersion does not have member field 'io.github.briqt.spark4j.constant.SparkApiVersion V4_0'
这是为啥啊，我查看源码确实有V4_0,但是运行就会报错
