### ISSUE TITLE
单元测试的时候，流式调用控制它i没有输出

### ISSUE THREAD

**Issue by taoshaolo** [briqt/xunfei-spark4j#15]
![image-20240923164940093](https://github.com/user-attachments/assets/96f59b51-831e-4cdd-bcf7-860772c4a223)

**Comment by briqt** [comment]
SparkClient的流式调用是异步执行的，请确保在单元测试结束之前，请求及响应能够完整的处理完毕。

建议在单元测试结尾默认加上  Thread.sleep(60000);
