### ISSUE TITLE
我在spring项目中作为依赖调用，但是显示 授权错误：该appId没有相关功能的授权或者业务量超过限制

### ISSUE THREAD

**Issue by DJL1n** [briqt/xunfei-spark4j#17]
![屏幕截图 2024-09-28 160000](https://github.com/user-attachments/assets/d0f85092-db0d-4db2-a912-982daa17515b)
zhesh这是我的调用代码，我id也申请下来了，连接的是无限量免费的lite

**Comment by briqt** [comment]
lite 对应  V1_5 版本，请使用  V1_5 试试

前段时间讯飞更新了版本的命名，本项目还没有替换

**Comment by DJL1n** [comment]
这个V1_5在哪里修改，我的调用函数没有关于这个的参数
不好意思不太看懂代码
