### ISSUE TITLE
请问如何捕捉异常？

### ISSUE THREAD

**Issue by zxxvscs** [briqt/xunfei-spark4j#6]
如题，如何捕捉异常？
我对这段代码进行异常捕捉，获取不到异常，然而异常却直接打印出来了
        
// 同步调用
SparkSyncChatResponse chatResponse = sparkDeskConfig.getSparkClient().chatSync(sparkRequest);

**Comment by briqt** [comment]
我确认了一下，确实存在同步调用无法捕获异常的问题。
已在 1.1.2 版本修复，正常捕获即可，参考readme的同步调用部分

**Comment by zxxvscs** [comment]
好的
